jadiblog/blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('blog', views.BlogListView.as_view(), name='blogpage'),
    path('post/create', views.PostCreateView.as_view(), name='create_post'),
    re_path('^post/update/(?P<slug>[^/]+)/?$', views.PostUpdateView.as_view(), name='update_post'),
    re_path('^post/(?P<slug>[^/]+)/?$', views.PostDetail.as_view(), name='post_detail'),

]

jadiblog/jadiblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from django.views.generic import TemplateView


urlpatterns = [
                path('', include('blog.urls')),
                path('users/', include('users.urls')),
                path('admin/', admin.site.urls),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jadiblog/users/urls.py
from django.urls import path,re_path
from . import views

app_name = 'users'

urlpatterns = [
    path('login', views.UsersLoginView.as_view(), name='login'),
    path('logout', views.UsersLogoutView.as_view(), name='logout'),

]

jadiblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.shortcuts import reverse


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Category, self).save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super(Tag, self).save(*args, **kwargs)


number_of_random_char = 16;


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True, allow_unicode=True, editable=False)
    description = models.TextField()
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts', blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    featured_image = models.ImageField(upload_to='post_image', blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, *args, **kwargs):
        new_slug = slugify(self.title, allow_unicode=True)
        if self.slug[:- (number_of_random_char + 1)] != new_slug:
            self.slug = new_slug + '-' + get_random_string(number_of_random_char)
        super(Post, self).save(*args, **kwargs)

jadiblog/users/models.py
from django.db import models

# Create your models here.

jadiblog/blog/views.py
from django.shortcuts import render
from django.views import generic
from . models import Post
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

NUMBER_RECENT_POSTS = 3


class HomeView(generic.ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = '-created_at'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent_post'] = Post.objects.all().order_by('-created_at')[:NUMBER_RECENT_POSTS]
        return context


class BlogListView(generic.ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = '-created_at'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(category__name='Blog')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent_post'] = Post.objects.all().order_by('-created_at')[:NUMBER_RECENT_POSTS]
        return context


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent_post'] = Post.objects.all().order_by('-created_at')[:NUMBER_RECENT_POSTS]
        return context


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    fields = ('title', 'description', 'category', 'tags', 'featured_image',)
    template_name = 'blog/create_post.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    fields = ('title', 'description', 'category', 'tags', 'featured_image',)
    template_name = 'blog/create_post.html'

jadiblog/users/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy


# Create your views here.


class UsersLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'registration/login.html'


class UsersLogoutView(LogoutView):
    next_page = 'blog:home'

jadiblog/blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block page_header %}
<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Read Our Blog</h2>
					</div>
				</div>
			</div>
		</aside>
{% endblock %}


{% block content %}
<div class="content">
	<form action="" method="POST" enctype="multipart/form-data">
		{%csrf_token%}
    {{ form|crispy }}
		<input class="btn btn-success" type="submit" value="Save Post">
	</form>

</div>
{% endblock %}

jadiblog/blog/templates/blog/home.html
{% extends 'base.html' %}
{% load humanize %}

{% block page_header %}
<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Read Our Blog</h2>
					</div>
				</div>
			</div>
		</aside>
{% endblock %}


{% block content %}
<div class="content">

	{% for post in posts %}
	<article class="blog-entry">
		<div class="blog-wrap">
			<span class="category text-center"><a href="blog.html">{{post.category}}</a></span>
			<h2 class="text-center"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
			<div class="blog-image">
				{% if post.featured_image %}
				<a href="{{post.get_absolute_url}}" class="blog-img text-center" style="background-image:url('{{post.featured_image.url}}');"><span><i class="icon-link"></i></span></a>
				{% endif %}
				<ul class="share">
				<li class="text-vertical"><i class="icon-share3"></i></li>
				<li><a href="#"><i class="icon-facebook"></i></a></li>
				<li><a href="#"><i class="icon-twitter"></i></a></li>
				<li><a href="#"><i class="icon-googleplus"></i></a></li>
			</ul>
			</div>
			<span class="category text-center"><a href="blog.html"><i class="icon-calendar3"></i>{{post.created_at|naturaltime}}</a> | <a href="blog.html" class="posted-by"><i class="icon-user2"></i> by {{post.author}}</a> | <a href="blog.html"><i class="icon-bubble3"></i> 5 Comments</a></span>
		</div>
		<div class="desc">
			<p class="first-letra">{{post.description|safe|truncatewords_html:65}}</p>
		</div>
		<p class="text-center"><a href="{{post.get_absolute_url}}" class="btn btn-primary btn-custom">Continue Reading</a></p>
	</article>
	{% endfor %}
	<div class="row">
		<div class="col-md-12 text-center">
			<ul class="pagination">
				<li class="disabled"><a href="#">&laquo;</a></li>
				<li class="active"><a href="#">1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">&raquo;</a></li>
			</ul>
		</div>
	</div>
</div>
{% endblock %}

jadiblog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block page_header %}
<aside id="colorlib-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12 breadcrumbs text-center">
						<h2>Read Our Blog</h2>
					</div>
				</div>
			</div>
		</aside>
{% endblock %}


{% block content %}
<div class="content">
	<article class="blog-entry">
		<div class="blog-wrap">
			<span class="category text-center"><a href="#">{{post.category}}</a></span>
			<h2 class="text-center"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
			{% if post.featured_image %}
				<a class="blog-img text-center" style="background-image:url('{{post.featured_image.url}}');"></a>
			{% endif %}
			<span class="category text-center"><a href="#"><i class="icon-calendar3"></i>{{post.created_at|naturaltime}}</a> | <a href="#" class="posted-by"><i class="icon-user2"></i> by {{post.author}}</a> | <a href="#"><i class="icon-bubble3"></i> 5 Comments</a></span>
		</div>
		<div class="desc">
			{{post.description|safe}}
		</div>
	</article>
	<div class="comment-box">
		<h2 class="colorlib-heading-2">3 Comments</h2>
		<div class="comment-post">
			<div class="user" style="background-image: url(images/person1.jpg);"></div>
			<div class="desc">
				<h3>Stephen Brent <span>Commented 5 days ago</span></h3>
				<p>A small river named Duden flows by their place and supplies. Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane.</p>
			</div>
		</div>
		<div class="comment-post">
			<div class="user" style="background-image: url(images/person2.jpg);"></div>
			<div class="desc">
				<h3>Stephen Brent <span>Commented 5 days ago</span></h3>
				<p>A small river named Duden flows by their place and supplies. Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane.</p>
			</div>
		</div>
		<div class="comment-post">
			<div class="user" style="background-image: url(images/person3.jpg);"></div>
			<div class="desc">
				<h3>Stephen Brent <span>Commented 5 days ago</span></h3>
				<p>A small river named Duden flows by their place and supplies. Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane.</p>
			</div>
		</div>
	</div>
	<div class="comment-area">
		<h2 class="colorlib-heading-2">Leave a comment</h2>
		<form action="#">
			<div class="row form-group">
				<div class="col-md-6">
					<!-- <label for="fname">First Name</label> -->
					<input type="text" id="fname" class="form-control" placeholder="Your firstname">
				</div>
				<div class="col-md-6">
					<!-- <label for="lname">Last Name</label> -->
					<input type="text" id="lname" class="form-control" placeholder="Your lastname">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="email">Email</label> -->
					<input type="text" id="email" class="form-control" placeholder="Your email address">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="subject">Subject</label> -->
					<input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<!-- <label for="message">Message</label> -->
					<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" value="Post Comment" class="btn btn-primary">
			</div>

		</form>
	</div>
</div>
{% endblock %}

jadiblog/templates/base.html
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Grand+Hotel" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Fira+Sans:100,200,300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
	{% load static %}
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Flaticons  -->
	<link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

    {% block headers %} {% endblock %}
    {% block title %}
        <title>Article Template</title>
    {% endblock %}


	</head>

	<body>

	<div class="colorlib-loader"></div>

	<div id="page">

        <!-- header -->
        {% include 'header.html' %}

		{% block page_header %} {% endblock %}

        <div id="colorlib-container">
            <div class="container">
                <div class="row">

					<!-- content -->
					{% block content %} {% endblock %}

					<!-- sidebar -->
					{% include 'sidebar.html' %}

				</div>
			</div>
		</div>

		<div id="colorlib-instagram">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 colorlib-heading text-center">
					<h2>Instagram</h2>
				</div>
			</div>
			<div class="row">
				<div class="instagram-entry">
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-1.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-2.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-3.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-4.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-5.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-6.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-7.jpg);">
					</a>
					<a href="#" class="instagram text-center" style="background-image: url(images/gallery-8.jpg);">
					</a>
				</div>
			</div>
		</div>

        <!-- footer -->
        {% include 'footer.html' %}



	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up2"></i></a>
	</div>

	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
	<!-- Owl carousel -->
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'js/main.js' %}"></script>

    {% block footers %} {% endblock %}

	</body>
</html>

jadiblog/templates/footer.html
<footer id="colorlib-footer" role="contentinfo">
			<div class="container">
				<div class="row row-pb-md">
					<div class="col-md-4">
						<h2>Navigational</h2>
						<p>
							<ul class="colorlib-footer-links">
								<li><a href="#"><i class="icon-check"></i> Home</a></li>
								<li><a href="#"><i class="icon-check"></i> About Me</a></li>
								<li><a href="#"><i class="icon-check"></i> Blog</a></li>
								<li><a href="#"><i class="icon-check"></i> Travel</a></li>
								<li><a href="#"><i class="icon-check"></i> Lifestyle</a></li>
								<li><a href="#"><i class="icon-check"></i> Fashion</a></li>
								<li><a href="#"><i class="icon-check"></i> Health</a></li>
							</ul>
						</p>
					</div>
					<div class="col-md-4">
						<h2>Recent Post</h2>
						<ul class="colorlib-footer-links">
							<li>
								<span>22 Jan, 2017</span>
								<a href="#">The Most Popular Leg Workout for Women</a>
							</li>
							<li>
								<span>20 Jan, 2017</span>
								<a href="#">Popular Lifestyle with Fashion &amp; Modeling</a>
							</li>
							<li>
								<span>21 Jan, 2017</span>
								<a href="#">Video Post Travel with my Friends</a>
							</li>
							<li>
								<span>20 Jan, 2017</span>
								<a href="#">Popular Lifestyle with Fashion &amp; Modeling</a>
							</li>
						</ul>
					</div>
					<div class="col-md-4 col-md-push-1">
						<h2>Tags</h2>
						<p class="tags">
							<span><a href="#"><i class="icon-tag"></i> Modeling</a></span>
							<span><a href="#"><i class="icon-tag"></i> Fashion</a></span>
							<span><a href="#"><i class="icon-tag"></i> Life</a></span>
							<span><a href="#"><i class="icon-tag"></i> Blog</a></span>
							<span><a href="#"><i class="icon-tag"></i> Workout</a></span>
							<span><a href="#"><i class="icon-tag"></i> Vacation</a></span>
							<span><a href="#"><i class="icon-tag"></i> Travel</a></span>
							<span><a href="#"><i class="icon-tag"></i> Exercise</a></span>
							<span><a href="#"><i class="icon-tag"></i> Health</a></span>
							<span><a href="#"><i class="icon-tag"></i> News</a></span>
							<span><a href="#"><i class="icon-tag"></i> Model</a></span>
							<span><a href="#"><i class="icon-tag"></i> Women</a></span>
							<span><a href="#"><i class="icon-tag"></i> Animals</a></span>
							<span><a href="#"><i class="icon-tag"></i> Nature</a></span>
							<span><a href="#"><i class="icon-tag"></i> Art</a></span>
							<span><a href="#"><i class="icon-tag"></i> Sea</a></span>
							<span><a href="#"><i class="icon-tag"></i> Ocean</a></span>
							<span><a href="#"><i class="icon-tag"></i> Office</a></span>
							<span><a href="#"><i class="icon-tag"></i> Home</a></span>
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<p>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
     					<small class="block">Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved. This template is made with <i class="icon-heart3" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></small>
    					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
					</div>
				</div>
			</div>
		</footer>

jadiblog/templates/header.html
<nav class="colorlib-nav" role="navigation">
			<div class="top-menu">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-2">
							<div id="colorlib-logo"><a href="{% url 'blog:home' %}">Article.</a></div>
						</div>
						<div class="col-xs-10 text-right menu-1">
							<ul>
								<li><a href="{% url 'blog:home' %}">Home</a></li>
								<li class="active"><a href="{% url 'blog:blogpage' %}">Blog</a></li>
								<li><a href="lifestyle.html">Podcast</a></li>
								<li><a href="travels.html">Videocast</a></li>
                                <li><a href="gallery.html">Projects</a></li>
								<li><a href="gallery.html">Donate</a></li>
								<li><a href="about.html">contact</a></li>
								{% if user.is_authenticated %}
								<li class="btn btn-info"><a href="#">Dashboard</a></li>
								{% else %}
								<li class="btn btn-success"><a href="#">Login</a></li>
								{% endif %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>

jadiblog/users/templates/users_base/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <title>
        {% block titile %}
        Star Admin Free Bootstrap Admin Dashboard Template
        {% endblock %}
   </title>

  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'users/css/vendors/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/vendors/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'users/css/vendors/vendor.bundle.addons.css' %}">
  <!-- endinject -->
  <!-- plugin css for this page -->
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
  <!-- endinject -->
  <link rel="shortcut icon" href="{% static 'users/images/favicon.png' %}" />

    {% block extra_css %}
    {% endblock %}
</head>

<body>
  <div class="container-scroller">
    {% block content %}
    {% endblock %}
  </div>
  <!-- container-scroller -->
  <!-- plugins:js -->
  <script src="{% static 'users/js/vendors/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'users/js/vendors/vendor.bundle.addons.js' %}"></script>
  <!-- endinject -->
  <!-- inject:js -->
  <script src="{% static 'users/js/off-canvas.js' %}"></script>
  <script src="{% static 'users/js/misc.js' %}"></script>
  <!-- endinject -->
    {% block extra_js %}
    {% endblock %}
</body>

</html>